### ISSUE TITLE
factory.LazyFunction not registered at the root module

### ISSUE THREAD

**Issue by kdeldycke** [rbarrois/factory_boy#272]
Tried to call the `LazyFunction` helper as [specified in the documentation](https://factoryboy.readthedocs.org/en/latest/reference.html?highlight=lazyfunction#lazyfunction), but it doesn't seems to be exposed by the `factory` module:
```python
>>> import factory
>>> factory.__version__
'2.6.1'
>>> factory.LazyAttribute
<class 'factory.declarations.LazyAttribute'>
>>> factory.LazyFunction
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'LazyFunction'
```

Is the documentation introduced by #267 wrong or should `LazyFunction` be exposed directly from the `factory` module?

**Comment by kdeldycke** [comment]
Ok, forget it. Everything's fine. Just that the documentation reference the development branch and #267 hasn't been released yet... :expressionless:
